os:
  - linux
language: node_js
node_js:
  - 14
dist: xenial
addons:
  chrome: stable
before_install:
  -  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
services:
  - xvfb

install:
  - yarn

before_script:
  - 'export DISPLAY=:99.0'
  - sleep 3 # give xvfb some time to start

script:
  - yarn test-travis

cache:
  directories:
    - node_modules

after_success: yarn coverage

notifications:
  email:
    on_success: never
    on_failure: change
