os:
  - linux
language: node_js
node_js:
  - 14

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3 # give xvfb some time to start

install:
  - yarn

script: yarn test-travis

cache:
  directories:
    - node_modules

after_success: yarn coverage
