os:
  - linux
language: node_js
node_js:
  - 14

services:
  - xvfb

install:
  - yarn

script:
  - yarn test-travis

cache:
  directories:
    - node_modules

after_success: yarn coverage

notifications:
  email:
    on_success: never
    on_failure: change
