version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Update yarn
          command: 'sudo yarn'
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/usr/local/lib/node_modules
      - run:
          name: Run tests
          command: yarn test-clci
