version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Update yarn
          command: 'sudo yarn'
      - restore_cache:
          key: '-v1-node-cache-{{ checksum "yarn.lock" }}-{{ arch }}'
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: '-v1-node-cache-{{ checksum "yarn.lock" }}-{{ arch }}'
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test-travis
