version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node-v1-{{ checksum "yarn.lock" }}
            - node-v1-
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: node-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test-clci
      - codecov/upload:
          file: './coverage/lcov.info'
